name: CI
on:
  push:
    branches: [ main ]
jobs:
  sync_to_gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git-sync
        run: |
          git remote set-url origin https://myml:${{ secrets.GITEE_TOKEN }}@gitee.com/myml/${{ github.event.repository.name }}.git
          git push --all origin
